import { defineCollection, z } from "astro:content";

const vins = defineCollection({
  type: "data",
  schema: ({ image }) =>
    z.object({
      nom: z.string(),
      couleur: z.enum(["Rouge", "Blanc", "Rosé"]),
      couleurTone: z.enum(["Rouge", "Blanc", "Rosé"]),
      appellation: z.string(),
      millesime: z.number().optional(),
      volume: z.number().default(75),
      prix: z.number(),
      stock: z
        .enum(["En stock", "Stock limité", "Rupture de stock"])
        .default("En stock"),
      description: z.string(),
      badges: z.array(z.string()).default([]),
      image: image(),
      imageAlt: z.string(),
      featured: z.boolean().default(false),
      ordre: z.number().default(99),
      locale: z.enum(["fr", "en", "es"]),
    }),
});

const visites = defineCollection({
  type: "data",
  schema: z.object({
    titre: z.string(),
    sousTitre: z.string(),
    prix: z.number(),
    perLabel: z.string().default("/ personne"),
    dureeMinutes: z.number(),
    capaciteMin: z.number().default(1),
    capaciteMax: z.number().default(12),
    langues: z.array(z.string()),
    inclus: z.array(z.string()),
    horaires: z.string(),
    joursOuverts: z.string(),
    politiqueAnnulation: z.string(),
    highlighted: z.boolean().default(false),
    badge: z.string().optional(),
    ordre: z.number().default(99),
    locale: z.enum(["fr", "en", "es"]),
  }),
});

const coffrets = defineCollection({
  type: "data",
  schema: ({ image }) =>
    z.object({
      nom: z.string(),
      meta: z.string(),
      description: z.string(),
      prixLabel: z.string(),
      image: image(),
      imageAlt: z.string(),
      badges: z.array(z.string()).default([]),
      tone: z.string().default("Coffret"),
      ctaLabel: z.string(),
      ctaHref: z.string(),
      ordre: z.number().default(99),
      locale: z.enum(["fr", "en", "es"]),
    }),
});

const domaine = defineCollection({
  type: "data",
  schema: ({ image }) =>
    z.object({
      theme: z.object({
        sectionDesktop: z.string(),
        sectionTablet: z.string(),
        sectionMobile: z.string(),
      }),
      seo: z.object({
        title: z.string(),
        description: z.string(),
      }),
      hero: z.object({
        eyebrow: z.string(),
        titleLines: z.tuple([z.string(), z.string()]),
        body: z.string(),
        primaryCta: z.object({ label: z.string(), href: z.string() }),
        secondaryCta: z.object({ label: z.string(), href: z.string() }),
        badges: z.array(z.string()),
        highlights: z.array(z.string()),
        image: image(),
        imageAlt: z.string(),
      }),
      terroir: z.object({
        eyebrow: z.string(),
        title: z.string(),
        body: z.string(),
        grapesTitle: z.string(),
        commitmentsTitle: z.string(),
        grapes: z.array(z.string()),
        commitments: z.array(z.object({ title: z.string(), body: z.string() })),
        image: image(),
        imageAlt: z.string(),
      }),
      family: z.object({
        eyebrow: z.string(),
        title: z.string(),
        body: z.array(z.string()),
        milestones: z.array(z.object({ year: z.string(), label: z.string() })),
        image: image(),
        imageAlt: z.string(),
      }),
      statsBar: z.array(z.object({ value: z.string(), label: z.string() })),
      visitCta: z.object({
        eyebrow: z.string(),
        title: z.string(),
        titleHighlight: z.string(),
        body: z.string(),
        details: z.array(z.string()),
        primaryCta: z.object({ label: z.string(), href: z.string() }),
        secondaryCta: z.object({ label: z.string(), href: z.string() }),
        image: image(),
        imageAlt: z.string(),
      }),
      wines: z.object({
        eyebrow: z.string(),
        title: z.string(),
        allLabel: z.string(),
        allHref: z.string(),
        items: z.array(z.object({
          image: image(),
          alt: z.string(),
          meta: z.string(),
          title: z.string(),
          body: z.string(),
          price: z.string(),
          ctaLabel: z.string(),
          ctaHref: z.string(),
        })),
      }),
      contact: z.object({
        eyebrow: z.string(),
        title: z.string(),
        body: z.string(),
        cards: z.array(z.object({
          label: z.string(),
          value: z.string(),
          href: z.string().optional(),
        })),
        cta: z.object({ label: z.string(), href: z.string() }),
      }),
    }),
});

const news = defineCollection({
  type: "data",
  schema: ({ image }) =>
    z.object({
      seo: z.object({ title: z.string(), description: z.string() }),
      theme: z.object({
        sectionDesktop: z.string(),
        sectionTablet: z.string(),
        sectionMobile: z.string(),
      }),
      hero: z.object({
        eyebrow: z.string(),
        titleLines: z.array(z.string()),
        lead: z.string(),
        primaryCta: z.object({ label: z.string(), href: z.string() }),
        metaItems: z.array(z.string()),
        image: image(),
        imageAlt: z.string(),
      }),
      featured: z.object({
        eyebrow: z.string(),
        category: z.string(),
        title: z.string(),
        excerpt: z.string(),
        date: z.string(),
        readTime: z.string(),
        ctaLabel: z.string(),
        ctaHref: z.string(),
        image: image(),
        imageAlt: z.string(),
      }),
      articles: z.object({
        eyebrow: z.string(),
        title: z.string(),
        chips: z.array(z.string()),
        activeChip: z.string(),
        leadCtaLabel: z.string(),
        leadCard: z.object({
          category: z.string(),
          date: z.string(),
          title: z.string(),
          excerpt: z.string(),
          readLabel: z.string(),
          href: z.string(),
          image: image(),
          imageAlt: z.string(),
        }),
        cards: z.array(z.object({
          category: z.string(),
          date: z.string(),
          title: z.string(),
          excerpt: z.string(),
          readLabel: z.string(),
          href: z.string(),
          image: image(),
          imageAlt: z.string(),
        })),
        viewMoreLabel: z.string(),
        viewMoreHref: z.string(),
      }),
      agenda: z.object({
        eyebrow: z.string(),
        title: z.string(),
        viewAllLabel: z.string(),
        viewAllHref: z.string(),
        events: z.array(z.object({
          day: z.string(),
          month: z.string(),
          type: z.string(),
          title: z.string(),
          time: z.string(),
          location: z.string(),
          href: z.string(),
        })),
      }),
      visitCta: z.object({
        eyebrow: z.string(),
        titleLines: z.array(z.string()),
        body: z.string(),
        ctaLabel: z.string(),
        ctaHref: z.string(),
        backgroundImage: image(),
        backgroundAlt: z.string(),
      }),
      blogPosts: z.array(z.object({
        headline: z.string(),
        description: z.string(),
        datePublished: z.string(),
        url: z.string(),
        category: z.string(),
      })),
    }),
});

const shop = defineCollection({
  type: "data",
  schema: ({ image }) =>
    z.object({
      seo: z.object({ title: z.string(), description: z.string() }),
      hero: z.object({
        image: image(),
        imageAlt: z.string(),
        eyebrow: z.string(),
        titleHtml: z.string(),
        body: z.string(),
        primaryCta: z.object({ label: z.string(), href: z.string() }),
        secondaryCta: z.object({ label: z.string(), href: z.string() }),
        metaAriaLabel: z.string(),
        metaItems: z.array(z.string()),
      }),
      compliance: z.object({
        marketingBannerAriaLabel: z.string(),
        marketingBannerTitle: z.string(),
        ageNotice: z.string(),
        healthNotice: z.string(),
        checkoutTitle: z.string(),
        checkoutAdultOnlyNote: z.string(),
        checkoutAcknowledgements: z.object({
          age: z.string(),
          information: z.string(),
        }),
        payOrderLabel: z.string(),
        payOrderHelp: z.string(),
        payOrderPendingLabel: z.string(),
      }),
      productGrid: z.object({
        eyebrow: z.string(),
        title: z.string(),
        previousLabel: z.string(),
        nextLabel: z.string(),
      }),
      domainSelection: z.object({
        eyebrow: z.string(),
        title: z.string(),
        items: z.array(z.object({
          icon: z.enum(["shipping", "map", "return", "lock", "support"]),
          title: z.string(),
          body: z.string(),
        })),
      }),
      caseComposer: z.object({
        backdropImage: image(),
        crateImage: image(),
        crateImageAlt: z.string(),
        eyebrow: z.string(),
        title: z.string(),
        intro: z.string(),
        offers: z.array(z.object({
          title: z.string(),
          lines: z.array(z.string()),
          price: z.string(),
          details: z.string(),
          ctaLabel: z.string(),
          ctaHref: z.string(),
        })),
      }),
      finalCta: z.object({
        sectionAriaLabel: z.string(),
        title: z.string(),
        body: z.string(),
        ctaLabel: z.string(),
        ctaHref: z.string(),
      }),
      faq: z.object({
        eyebrow: z.string(),
        title: z.string(),
        items: z.array(z.object({
          question: z.string(),
          answer: z.string(),
        })),
      }),
      confirmationPage: z.object({
        seo: z.object({ title: z.string(), description: z.string() }),
        hero: z.object({ title: z.string(), body: z.string() }),
        status: z.object({ labelPaid: z.string(), labelRefPrefix: z.string() }),
        nextSteps: z.object({
          title: z.string(),
          items: z.array(z.string()),
        }),
        support: z.object({
          title: z.string(),
          body: z.string(),
          emailLabel: z.string(),
          phoneLabel: z.string(),
        }),
        actions: z.object({
          backShopLabel: z.string(),
          backHomeLabel: z.string(),
        }),
        legal: z.object({ moderationNotice: z.string() }),
      }),
    }),
});

const visits = defineCollection({
  type: "data",
  schema: ({ image }) =>
    z.object({
      seo: z.object({ title: z.string(), description: z.string() }),
      hero: z.object({
        eyebrow: z.string(),
        titleLines: z.tuple([z.string(), z.string()]),
        body: z.string(),
        badges: z.array(z.object({ icon: z.enum(["clock", "ticket", "globe", "calendar", "car"]), label: z.string() })),
        primaryCta: z.object({ label: z.string(), href: z.string() }),
        secondaryCta: z.object({ label: z.string(), href: z.string() }),
        helper: z.string(),
        image: image(),
        imageAlt: z.string(),
      }),
      trustBar: z.array(z.string()),
      timeline: z.object({
        eyebrow: z.string(),
        title: z.string(),
        body: z.string(),
        steps: z.array(z.object({
          id: z.string(),
          number: z.string(),
          title: z.string(),
          body: z.string(),
          image: image(),
          imageAlt: z.string(),
          layout: z.object({
            mediaRatio: z.string(),
            mediaMaxWidth: z.string(),
            contentMaxWidth: z.string(),
            align: z.enum(["start", "center"]).optional(),
          }),
        })),
      }),
      wines: z.object({
        eyebrow: z.string(),
        title: z.string(),
        body: z.string(),
        cards: z.array(z.object({
          id: z.string(),
          tag: z.string(),
          tagTone: z.enum(["rose", "white", "red"]),
          title: z.string(),
          notes: z.array(z.string()),
          image: image(),
          imageAlt: z.string(),
        })),
      }),
      pairing: z.object({
        image: image(),
        imageAlt: z.string(),
        eyebrow: z.string(),
        title: z.tuple([z.string(), z.string()]),
        body: z.string(),
        bullets: z.array(z.string()),
        note: z.string(),
      }),
      pricing: z.object({
        eyebrow: z.string(),
        title: z.string(),
        body: z.string(),
        layout: z.object({
          containerMaxWidth: z.string(),
          cardMinHeight: z.string(),
          cardPadding: z.string(),
          titleSize: z.string(),
          priceSize: z.string(),
        }),
        meta: z.array(z.string()),
      }),
      access: z.object({
        eyebrow: z.string(),
        title: z.string(),
        body: z.string(),
        leftCard: z.object({
          icon: z.enum(["pin", "car", "plane", "train"]),
          tag: z.string(),
          title: z.string(),
          subtitle: z.string(),
          content: z.array(z.string()),
          ctaLabel: z.string(),
          ctaHref: z.string(),
        }),
        rightCards: z.array(z.object({
          icon: z.enum(["pin", "car", "plane", "train"]),
          tag: z.string(),
          title: z.string(),
          subtitle: z.string(),
          content: z.array(z.string()),
        })),
      }),
      escape: z.object({
        image: image(),
        imageAlt: z.string(),
        layout: z.object({
          backgroundImage: image(),
          overlayOpacity: z.number(),
          imagePanelRadius: z.string(),
        }),
        eyebrow: z.string(),
        title: z.tuple([z.string(), z.string()]),
        body: z.string(),
        features: z.array(z.object({ icon: z.enum(["tree", "pool", "event"]), label: z.string() })),
        cta: z.object({ label: z.string(), href: z.string() }),
      }),
      booking: z.object({
        eyebrow: z.string(),
        title: z.string(),
        body: z.string(),
        layout: z.object({
          calendarWidthRatio: z.string(),
          controlsWidthRatio: z.string(),
          panelMaxWidth: z.string(),
          calendarCellHeight: z.string(),
          controlRowHeight: z.string(),
        }),
        ui: z.object({
          prevMonthAriaLabel: z.string(),
          nextMonthAriaLabel: z.string(),
          slotHeading: z.string(),
          participantsHeading: z.string(),
          priceFromLabel: z.string(),
          pricePerPersonLabel: z.string(),
          missingDateMessage: z.string(),
          defaultSuccessMessage: z.string(),
          defaultErrorMessage: z.string(),
          mailSubjectFallback: z.string(),
        }),
        config: z.object({
          monthLabel: z.string(),
          initialMonth: z.string(),
          locale: z.string(),
          timezone: z.string(),
          startDate: z.string(),
          endDate: z.string(),
          dayLabels: z.array(z.string()),
          selectableDays: z.array(z.number()),
          disabledWeekdays: z.array(z.number()).default([]),
          disabledDates: z.array(z.string()).default([]),
          defaultDay: z.number(),
          slots: z.array(z.object({ id: z.string(), label: z.string() })),
          defaultSlotId: z.string(),
          minParticipants: z.number(),
          maxParticipants: z.number(),
          defaultParticipants: z.number(),
          addonLabel: z.string(),
          basePricePerPerson: z.number(),
          addonPricePerPerson: z.number(),
          ctaLabel: z.string(),
          ctaHref: z.string(),
          callLabel: z.string(),
          submitEndpoint: z.string(),
          successMessage: z.string(),
          errorMessage: z.string(),
        }),
      }),
      finalCta: z.object({
        image: image(),
        imageAlt: z.string(),
        layout: z.object({
          contentMaxWidth: z.string(),
          eyebrowToTitleGap: z.string(),
          titleToBodyGap: z.string(),
          sectionMinHeight: z.string(),
        }),
        eyebrow: z.string(),
        title: z.string(),
        body: z.string(),
      }),
    }),
});

const site = defineCollection({
  type: "data",
  schema: ({ image }) =>
    z.object({
      nav: z.array(z.object({
        label: z.string(),
        href: z.string(),
        mobile: z.boolean().optional(),
        desktopSlot: z.enum(["left", "right"]).optional(),
        desktopLabel: z.string().optional(),
      })),
      mobileQuickActions: z.array(z.object({
        id: z.enum(["book", "shop", "call"]),
        label: z.string(),
        href: z.string(),
        icon: z.enum(["calendar", "bag", "phone"]),
        priority: z.enum(["primary", "secondary"]),
      })),
      hero: z.object({
        eyebrow: z.string(),
        title: z.array(z.string()),
        body: z.string(),
        ctaLabel: z.string(),
        ctaHref: z.string(),
        meta: z.array(z.string()),
        backgroundImage: image(),
        featuredCards: z.array(z.object({
          kicker: z.string(),
          title: z.string(),
          image: image(),
          alt: z.string(),
          href: z.string(),
        })),
      }),
      reasons: z.object({
        eyebrow: z.string(),
        title: z.string(),
        items: z.array(z.object({
          title: z.string(),
          body: z.string(),
          icon: z.string(),
        })),
      }),
      experience: z.object({
        eyebrow: z.string(),
        title: z.string(),
        body: z.string(),
        details: z.array(z.object({
          label: z.string(),
          value: z.string(),
          icon: z.string(),
        })),
        infoLine: z.string(),
        ctaLabel: z.string(),
        ctaHref: z.string(),
        backgroundImage: image(),
      }),
      gallery: z.object({
        eyebrow: z.string(),
        title: z.string(),
        items: z.array(z.object({
          src: image(),
          alt: z.string(),
        })),
      }),
      testimonials: z.object({
        eyebrow: z.string(),
        title: z.string(),
        pressLabel: z.string(),
        pressLogos: z.array(z.string()),
        items: z.array(z.object({
          quote: z.string(),
          author: z.string(),
          meta: z.string(),
          rating: z.number(),
        })),
      }),
      history: z.object({
        eyebrow: z.string(),
        title: z.string(),
        titleHighlight: z.string(),
        body: z.array(z.string()),
        imagePrimary: image(),
        ctaLabel: z.string(),
        ctaHref: z.string(),
      }),
      wines: z.object({
        eyebrow: z.string(),
        title: z.string(),
        allWinesLabel: z.string(),
        allWinesHref: z.string(),
        items: z.array(z.object({
          image: image(),
          title: z.string(),
          subtitle: z.string(),
          description: z.string(),
          ctaLabel: z.string(),
          ctaHref: z.string(),
        })),
      }),
      contact: z.object({
        eyebrow: z.string(),
        titleHtml: z.string(),
        body: z.string(),
        info: z.array(z.object({
          label: z.string(),
          value: z.string(),
          icon: z.string(),
        })),
        labels: z.object({
          firstName: z.string(),
          lastName: z.string(),
          email: z.string(),
          phone: z.string(),
          subject: z.string(),
          message: z.string(),
          submit: z.string(),
        }),
        validation: z.object({
          required: z.string(),
          invalidEmail: z.string(),
          fixErrors: z.string(),
        }),
        mail: z.object({
          defaultSubject: z.string(),
          fieldFirstName: z.string(),
          fieldLastName: z.string(),
          fieldEmail: z.string(),
          fieldPhone: z.string(),
          fieldMessage: z.string(),
        }),
        formSuccessMessage: z.string(),
        formErrorMessage: z.string(),
      }),
      footer: z.object({
        brandTitle: z.string(),
        about: z.string(),
        groups: z.array(z.object({
          title: z.string(),
          links: z.array(z.object({
            label: z.string(),
            href: z.string(),
          })),
        })),
        newsletterTitle: z.string(),
        newsletterBody: z.string(),
        newsletterAdultNotice: z.string(),
        newsletterPlaceholder: z.string(),
        newsletterAction: z.string(),
        social: z.array(z.object({
          label: z.string(),
          href: z.string(),
        })),
        copyright: z.string(),
        legalLine: z.string(),
      }),
    }),
});

const ui = defineCollection({
  type: "data",
  schema: z.object({
    skipToContent: z.string(),
    navLabel: z.string(),
    mobileNavLabel: z.string(),
    menuOpen: z.string(),
    menuClose: z.string(),
    homeLabel: z.string(),
    languageLabel: z.string(),
    bookCta: z.string(),
    callCta: z.string(),
    shopCta: z.string(),
    backToTop: z.string(),
    formSubmitting: z.string(),
    formSuccess: z.string(),
    formError: z.string(),
    required: z.string(),
    invalidEmail: z.string(),
    legalLine: z.string(),
    copyright: z.string(),
  }),
});

const contact = defineCollection({
  type: "data",
  schema: z.object({
    phone: z.string(),
    phoneTel: z.string(),
    email: z.string(),
    website: z.string(),
    address: z.string(),
    region: z.string(),
    city: z.string(),
    mapUrl: z.string(),
    instagram: z.string(),
    facebook: z.string(),
  }),
});

export const collections = { vins, visites, coffrets, domaine, news, shop, visits, site, ui, contact };
